apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-socat.fullname" . }}
  labels:
    {{- include "k8s-socat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-proxy
      protocol: TCP
      name: tcp-proxy
  selector:
    {{- include "k8s-socat.selectorLabels" . | nindent 4 }}
